name: Issues Closer

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v2.0.0
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}
          stale-issue-label: 'Type: Stand Up'
          days-before-stale: 1
          days-before-close: 1
          debug-only: true
