name: Issues Creator

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: wesleytodd/meeting-maker@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          schedules: 2020-05-04T09:00:00+03/P1D
          createWithin: P30M
          issueTitle: [daily stand up] <%= date.toFormat('dd-MM-yyyy') %>
          issueTemplate: .github/stand-up.md
          labels: 'Type: Stand Up'
