name: Test Action

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262

      - name: Test launcher
        working-directory: .github/scripts/dsm-launcher
        run: cargo test --locked

      - name: Test Action contract
        run: .github/scripts/tests/run-action.sh
